return { --> List of song names as strings
    "I Wonder",
	"Jennifer's Bloxy", 
	"Creep", 
	"From The Start",
	"Thick of it", 
	"Just The Two Of Us", 
	"Like That", 
	"Better Off Alone", 
	"Untrust Us", 
	"Chamber Of Reflection", 
	"Family Business", 
	"Space Song", 
	"Blood on The Leaves", 
	"Me and the Birds", 
	"All of The Lights", 
	"Sleepwalker", 
	"Heck of A Life", 
	"EARFQUAKE", 
	"Kerosene", 
}